# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ml_est <- function(est, tau, yi, vi, ycv) {
    .Call(`_TEST_ml_est`, est, tau, yi, vi, ycv)
}

rcpp_hello_world <- function() {
    .Call(`_TEST_rcpp_hello_world`)
}

